"""Database package for Customer Workflow Automation System."""

from src.db.models import (
    Approval,
    ApprovalStatus,
    Base,
    Campaign,
    CampaignStatus,
    Customer,
    CustomerSegment,
    CustomerStatus,
    CustomerType,
    EmailLog,
    FollowUp,
    FollowUpStatus,
    Interaction,
    InteractionType,
    PaymentStatus,
    Reminder,
    ScheduledWorkflow,
    ScheduledWorkflowExecution,
    ScheduledWorkflowFrequency,
    ScheduledWorkflowStatus,
    SupportStatus,
    Task,
    TaskStatus,
    WorkflowExecution,
    WorkflowStatus,
)

from src.db.repositories import (
    ApprovalRepository,
    CampaignRepository,
    CustomerRepository,
    EmailLogRepository,
    FollowUpRepository,
    InteractionRepository,
    ReminderRepository,
    ScheduledWorkflowExecutionRepository,
    ScheduledWorkflowRepository,
    TaskRepository,
    WorkflowExecutionRepository,
)

from src.db.service import DatabaseService, db_service, get_db, init_database, reset_database

__all__ = [
    # Models
    "Base",
    "Customer",
    "CustomerStatus",
    "CustomerSegment",
    "CustomerType",
    "PaymentStatus",
    "SupportStatus",
    "Interaction",
    "InteractionType",
    "Task",
    "TaskStatus",
    "Reminder",
    "WorkflowExecution",
    "WorkflowStatus",
    "Approval",
    "ApprovalStatus",
    "Campaign",
    "CampaignStatus",
    "EmailLog",
    "FollowUp",
    "FollowUpStatus",
    "ScheduledWorkflow",
    "ScheduledWorkflowExecution",
    "ScheduledWorkflowFrequency",
    "ScheduledWorkflowStatus",
    # Repositories
    "CustomerRepository",
    "InteractionRepository",
    "TaskRepository",
    "ReminderRepository",
    "WorkflowExecutionRepository",
    "ApprovalRepository",
    "CampaignRepository",
    "EmailLogRepository",
    "FollowUpRepository",
    "ScheduledWorkflowRepository",
    "ScheduledWorkflowExecutionRepository",
    # Service
    "DatabaseService",
    "db_service",
    "get_db",
    "init_database",
    "reset_database",
]